server:
  port: 8800


spring:
#  数据源配置
    datasource:
        url: jdbc:mysql://localhost:3306/xxxxx?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
        username: xxxxx
        password: xxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
#上传文件大小限制
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB


mybatis-plus:
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭驼峰命名   如果开启驼峰命名请注释此配置
    map-underscore-to-camel-case: false


  # TODO 腾讯云对象存储配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx


# TODO minio对象存储配置  自行部署minio服务
minio:
  endpoint: xxxxxx
  accessKey: xxxxxx
  secretKey: xxxxxx
  bucket: xxxxxxx


# TODO 选择使用的对象存储 默认使用minio
# MinioManager  minio对象存储 需要自行部署
# CosManager    腾讯云对象存储
file:
  manager: MinioManager
    # manager: CosManager


# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - top.qtcc.qiutuanallpowerfulspringboot.controller
